defaults: &defaults
  adapter: mysql2
  username: root
  password: akira45r
  host: localhost

development:
  database: orderizer_dev
  <<: *defaults

test: &test
  database: orderizer_production
  <<: *defaults

staging:
  database: orderizer_staging
  <<: *defaults

production:
  database: orderizer_live
  <<: *defaults


